import { PlayerStats, Player } from "../shared/types";

export const players: Player[] = [
  {
    playerId: 1,
    name: "Lionel Messi",
    birthdate: "1987-06-24",
    nationality: "Argentina",
  },
  {
    playerId: 2,
    name: "Cristiano Ronaldo",
    birthdate: "1985-02-05",
    nationality: "Portugal",
  },
  {
    playerId: 3,
    name: "Kevin De Bruyne",
    birthdate: "1991-06-28",
    nationality: "Belgium",
  },
  {
    playerId: 4,
    name: "Virgil van Dijk",
    birthdate: "1991-07-08",
    nationality: "Netherlands",
  },
  {
    playerId: 5,
    name: "Kylian Mbappe",
    birthdate: "1998-12-20",
    nationality: "France",
  },
  {
    playerId: 6,
    name: "Neymar Jr.",
    birthdate: "1992-02-05",
    nationality: "Brazil",
  },
  {
    playerId: 7,
    name: "Robert Lewandowski",
    birthdate: "1988-08-21",
    nationality: "Poland",
  },
  {
    playerId: 8,
    name: "Luka Modric",
    birthdate: "1985-09-09",
    nationality: "Croatia",
  }
];

export const playerStats: PlayerStats[] = [
  {
    playerId: 1,
    seasonYear: "2023-2024",
    team: "Inter Miami",
    position: "Forward",
    goalsScored: 15,
    assists: 7,
    appearances: 28,
    description: "Excelled in attack, scoring key goals and creating chances in high-pressure matches.",
  },
  {
    playerId: 1,
    seasonYear: "2022-2023",
    team: "Paris Saint-Germain",
    position: "Forward",
    goalsScored: 18,
    assists: 6,
    appearances: 30,
    description: "A key figure in PSG's offensive play, consistently finding the back of the net.",
  },
  {
    playerId: 2,
    seasonYear: "2023-2024",
    team: "Al-Nassr",
    position: "Forward",
    goalsScored: 17,
    assists: 4,
    appearances: 30,
    description: "A crucial player for Al-Nassr, consistently scoring goals and leading the team's offense.",
  },
  {
    playerId: 2,
    seasonYear: "2022-2023",
    team: "Al-Nassr",
    position: "Forward",
    goalsScored: 22,
    assists: 3,
    appearances: 29,
    description: "Despite challenges, Ronaldo maintained his reputation as a prolific goal-scorer.",
  },
  {
    playerId: 3,
    seasonYear: "2023-2024",
    team: "Manchester City",
    position: "Midfielder",
    goalsScored: 6,
    assists: 12,
    appearances: 25,
    description: "Outstanding playmaker, controlling the midfield and setting up numerous goal-scoring opportunities.",
  },
  {
    playerId: 3,
    seasonYear: "2022-2023",
    team: "Manchester City",
    position: "Midfielder",
    goalsScored: 5,
    assists: 10,
    appearances: 28,
    description: "An essential part of Manchester City's attacking strategy with his vision and passing.",
  },
  {
    playerId: 4,
    seasonYear: "2023-2024",
    team: "Liverpool",
    position: "Defender",
    goalsScored: 2,
    assists: 1,
    appearances: 27,
    description: "A rock in defense, leading Liverpool's backline with skillful tackles and positioning.",
  },
  {
    playerId: 4,
    seasonYear: "2022-2023",
    team: "Liverpool",
    position: "Defender",
    goalsScored: 4,
    assists: 2,
    appearances: 29,
    description: "A dominant presence in defense and a consistent performer for Liverpool.",
  },
  {
    playerId: 5,
    seasonYear: "2023-2024",
    team: "Paris Saint-Germain",
    position: "Forward",
    goalsScored: 21,
    assists: 5,
    appearances: 29,
    description: "Lightning fast on the counter-attack, Mbappe was PSG's top scorer this season.",
  },
  {
    playerId: 5,
    seasonYear: "2022-2023",
    team: "Paris Saint-Germain",
    position: "Forward",
    goalsScored: 23,
    assists: 6,
    appearances: 31,
    description: "A constant threat on the pitch, Mbappe's pace and finishing were unmatched.",
  },
  {
    playerId: 6,
    seasonYear: "2023-2024",
    team: "Al Hilal",
    position: "Forward",
    goalsScored: 10,
    assists: 8,
    appearances: 22,
    description: "Known for his dribbling and creativity, Neymar provided crucial goals and assists.",
  },
  {
    playerId: 6,
    seasonYear: "2022-2023",
    team: "Paris Saint-Germain",
    position: "Forward",
    goalsScored: 15,
    assists: 9,
    appearances: 27,
    description: "A standout in the attacking third, Neymar showcased his flair and playmaking ability.",
  },
  {
    playerId: 7,
    seasonYear: "2023-2024",
    team: "Barcelona",
    position: "Forward",
    goalsScored: 18,
    assists: 3,
    appearances: 28,
    description: "Reliable goal-scorer for Barcelona, constantly pressuring opponents' defenses.",
  },
  {
    playerId: 7,
    seasonYear: "2022-2023",
    team: "Barcelona",
    position: "Forward",
    goalsScored: 25,
    assists: 4,
    appearances: 29,
    description: "Lewandowski had another phenomenal season, maintaining his status as one of the best strikers in the world.",
  },
  {
    playerId: 8,
    seasonYear: "2023-2024",
    team: "Real Madrid",
    position: "Midfielder",
    goalsScored: 3,
    assists: 10,
    appearances: 26,
    description: "A visionary on the field, Modric expertly orchestrated the midfield for Real Madrid.",
  },
  {
    playerId: 8,
    seasonYear: "2022-2023",
    team: "Real Madrid",
    position: "Midfielder",
    goalsScored: 2,
    assists: 8,
    appearances: 28,
    description: "A consistent performer with his sharp passing and work ethic in the midfield.",
  }
];
